package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"io"
	"math"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type Material struct { ID string `json:"id"`; Name string `json:"name"`; Tier string `json:"tier"`; Kind string `json:"kind"`; SignalRS int `json:"signal_rs"`; Quality *float64 `json:"quality,omitempty"`; Notes string `json:"notes,omitempty"` }
type Inventory struct { MaterialID string `json:"material_id"`; Quantity float64 `json:"quantity"`; Quality float64 `json:"quality"` }
type BlueprintMaterial struct { MaterialID string `json:"material_id"`; Quantity float64 `json:"quantity"`; MinQuality float64 `json:"min_quality,omitempty"` }
type Blueprint struct { ID string `json:"id"`; Name string `json:"name"`; Output string `json:"output"`; Quantity float64 `json:"quantity"`; Tracked bool `json:"tracked"`; Materials []BlueprintMaterial `json:"materials"`; Notes string `json:"notes,omitempty"` }
type PlanItem struct { BlueprintID string `json:"blueprint_id"`; Crafts float64 `json:"crafts"` }
type Data struct { Version int `json:"version"`; Patch string `json:"patch"`; Materials []Material `json:"materials"`; Inventory []Inventory `json:"inventory"`; Blueprints []Blueprint `json:"blueprints"`; Plan []PlanItem `json:"plan"` }
type App struct { data Data; dataDir string; screen, selected int; filter, message, scan string; quitting bool; scanRows []ScanResult }
type ScanResult struct { Material Material; Count int; Error float64 }

func main(){ dir,err:=defaultDataDir(); if err!=nil{fatal(err)}; app,err:=load(dir);if err!=nil{fatal(err)};if err:=rawMode();err!=nil{fatal(err)};defer restoreMode();app.loop() }
func defaultDataDir()(string,error){if p:=os.Getenv("SCWIKI_DATA");p!=""{return p,os.MkdirAll(p,0755)};h,e:=os.UserHomeDir();if e!=nil{return "",e};d:=filepath.Join(h,".local","share","scwiki");return d,os.MkdirAll(d,0755)}
func load(dir string)(*App,error){p:=filepath.Join(dir,"wiki.json");b,e:=os.ReadFile(p);if os.IsNotExist(e){d:=Data{Version:1,Patch:"4.10",Materials:seedMaterials()};if e=saveData(dir,d);e!=nil{return nil,e};return &App{data:d,dataDir:dir},nil};if e!=nil{return nil,e};var d Data;if e=json.Unmarshal(b,&d);e!=nil{return nil,e};if d.Version==0{d.Version=1};return &App{data:d,dataDir:dir},nil}
func saveData(dir string,d Data)error{b,e:=json.MarshalIndent(d,"","  ");if e!=nil{return e};p:=filepath.Join(dir,"wiki.json.tmp");if e=os.WriteFile(p,append(b,'\n'),0644);e!=nil{return e};return os.Rename(p,filepath.Join(dir,"wiki.json"))}
func(a *App)save(){if e:=saveData(a.dataDir,a.data);e!=nil{a.message="save failed: "+e.Error()}else{a.message="saved"}}
func(a *App)loop(){for !a.quitting{a.render();k,e:=readKey(os.Stdin);if e!=nil{return};a.handle(k)}}
func(a *App)handle(k byte){switch k{case'q','Q':a.quitting=true;case'1':a.screen=0;a.selected=0;a.filter="";case'2':a.screen=1;a.selected=0;a.filter="";case'3':a.screen=2;case'4':a.screen=3;a.selected=0;a.filter="";case'5':a.screen=4;a.selected=0;a.filter="";case'j','J':a.move(1);case'k','K':a.move(-1);case'g':a.selected=0;case'G':a.moveToEnd();case't','T':if a.screen==4{a.togglePlan()}else{a.toggleTrack()};case'a','A':if a.screen==4{a.setPlanCrafts()}else{a.addInventory()};case'/':a.promptFilter();case'r','R':a.scanPrompt();case's','S':a.save();case'c','C':a.filter="";a.selected=0;case'x','X':a.removePlanItem()}}
func(a *App)move(d int){n:=a.itemCount();if n==0{return};a.selected+=d;if a.selected<0{a.selected=0};if a.selected>=n{a.selected=n-1}}
func(a *App)moveToEnd(){if n:=a.itemCount();n>0{a.selected=n-1}}
func(a *App)itemCount()int{switch a.screen{case 0:return len(a.filteredMaterials());case 1:return len(a.filteredBlueprints());case 3:return len(a.trackedMaterials());case 4:return len(a.filteredPlanBlueprints())};return 0}
func(a *App)toggleTrack(){if a.screen==0{r:=a.filteredMaterials();if a.selected>=len(r){return};m:=r[a.selected];if a.inventory(m.ID)==nil{a.data.Inventory=append(a.data.Inventory,Inventory{MaterialID:m.ID});a.message="tracked: "+m.Name}else{a.data.Inventory=removeInventory(a.data.Inventory,m.ID);a.message="untracked: "+m.Name};a.save()}else if a.screen==1{r:=a.filteredBlueprints();if a.selected>=len(r){return};id:=r[a.selected].ID;for i:=range a.data.Blueprints{if a.data.Blueprints[i].ID==id{a.data.Blueprints[i].Tracked=!a.data.Blueprints[i].Tracked;a.message="blueprint tracking updated";break}};a.save()}}
func(a *App)addInventory(){if a.screen!=0{a.message="select a material first";return};r:=a.filteredMaterials();if a.selected>=len(r){return};m:=r[a.selected];line,e:=linePrompt(fmt.Sprintf("%s quantity quality (e.g. 12.5 85): ",m.Name));if e!=nil{return};f:=strings.Fields(line);if len(f)<2{a.message="expected quantity and quality";return};q,e1:=strconv.ParseFloat(f[0],64);qual,e2:=strconv.ParseFloat(f[1],64);if e1!=nil||e2!=nil||q<0||qual<0||qual>1000{a.message="invalid quantity/quality";return};if x:=a.inventory(m.ID);x!=nil{x.Quantity=q;x.Quality=qual}else{a.data.Inventory=append(a.data.Inventory,Inventory{MaterialID:m.ID,Quantity:q,Quality:qual})};a.save()}
func(a *App)promptFilter(){if s,e:=linePrompt("filter: ");e==nil{a.filter=strings.TrimSpace(s);a.selected=0}}
func(a *App)scanPrompt(){s,e:=linePrompt("RS signal: ");if e!=nil{return};a.scan=strings.TrimSpace(s);v,e:=strconv.Atoi(strings.ReplaceAll(a.scan,",",""));if e!=nil{a.message="invalid RS";a.scanRows=nil;return};a.scanRows=a.scanMatch(v);a.screen=2}
func(a *App)togglePlan(){r:=a.filteredPlanBlueprints();if a.selected>=len(r){return};id:=r[a.selected].ID;for i,x:=range a.data.Plan{if x.BlueprintID==id{a.data.Plan=append(a.data.Plan[:i],a.data.Plan[i+1:]...);a.message="removed from plan";a.save();return}};a.data.Plan=append(a.data.Plan,PlanItem{BlueprintID:id,Crafts:1});a.message="added to plan";a.save()}
func(a *App)setPlanCrafts(){r:=a.filteredPlanBlueprints();if a.selected>=len(r){return};id:=r[a.selected].ID;line,e:=linePrompt("output units (0 removes): ");if e!=nil{return};v,e:=strconv.ParseFloat(strings.TrimSpace(line),64);if e!=nil||v<0{a.message="invalid craft quantity";return};for i:=range a.data.Plan{if a.data.Plan[i].BlueprintID==id{if v==0{a.data.Plan=append(a.data.Plan[:i],a.data.Plan[i+1:]...)}else{a.data.Plan[i].Crafts=v};a.save();return}};if v>0{a.data.Plan=append(a.data.Plan,PlanItem{BlueprintID:id,Crafts:v});a.save()}}
func(a *App)removePlanItem(){if a.screen!=4{return};r:=a.filteredPlanBlueprints();if a.selected>=len(r){return};id:=r[a.selected].ID;for i,x:=range a.data.Plan{if x.BlueprintID==id{a.data.Plan=append(a.data.Plan[:i],a.data.Plan[i+1:]...);a.message="removed from plan";a.save();return}}}
func(a *App)render(){clearScreen();w,h:=termSize();fmt.Printf("SCWIKI • local Star Citizen wiki • patch %s\n",a.data.Patch);fmt.Println("1 Materials  2 Blueprints  3 Scanner  4 Tracked  5 Planner     j/k move  / filter  t plan  a crafts  x remove  r scan  s save  q quit");fmt.Println(strings.Repeat("─",min(w,120)));switch a.screen{case 0:a.renderMaterials(h);case 1:a.renderBlueprints(h);case 2:a.renderScanner(h);case 3:a.renderTracked(h);case 4:a.renderPlanner(h)};fmt.Println(strings.Repeat("─",min(w,120)));if a.message!=""{fmt.Println(a.message)}}
func(a *App)renderMaterials(h int){r:=a.filteredMaterials();fmt.Printf("MATERIALS [%d]\n\n%-20s %-4s %-18s %8s %8s\n","filtered",len(r),"NAME","TIER","KIND","BASE RS","TRACKED");s,e:=window(a.selected,len(r),h-7);for i:=s;i<e;i++{m:=r[i];tr:="no";if a.inventory(m.ID)!=nil{tr="yes"};fmt.Printf("%s%-20s %-4s %-18s %8d %8s\n",selmark(i,a.selected),m.Name,m.Tier,m.Kind,m.SignalRS,tr)}}
func(a *App)renderBlueprints(h int){r:=a.filteredBlueprints();fmt.Printf("BLUEPRINTS [%d]\n\n%-28s %-20s %8s\n","filtered",len(r),"NAME","OUTPUT","TRACKED");s,e:=window(a.selected,len(r),h-13);for i:=s;i<e;i++{b:=r[i];tr:="no";if b.Tracked{tr="yes"};fmt.Printf("%s%-28s %-20s %8s\n",selmark(i,a.selected),b.Name,b.Output,tr)};if len(r)==0{return};b:=r[a.selected];fmt.Printf("\nSELECTED: %s -> %s x%.2f\n%-18s %10s %10s %10s %10s\n","",b.Output,b.Quantity,"MATERIAL","REQUIRED","OWNED","QUALITY","MIN Q");for _,req:=range b.Materials{m:=a.materialByID(req.MaterialID);if m==nil{continue};owned,qual:=0.,0.;if inv:=a.inventory(req.MaterialID);inv!=nil{owned,qual=inv.Quantity,inv.Quality};minq:="-";if req.MinQuality>0{minq=fmt.Sprintf("%.0f",req.MinQuality)};status:="";if owned+1e-9<req.Quantity{status=" *NEED*"};fmt.Printf("%-18s %10.2f %10.2f %10.0f %10s%s\n",m.Name,req.Quantity,owned,qual,minq,status)}}
func(a *App)renderScanner(h int){fmt.Printf("SCANNER\n\nRS signal: %s\n\n",a.scan);if len(a.scanRows)==0{fmt.Println("Press r and enter the RS value shown by your ship scanner.");return};fmt.Printf("%-18s %8s %8s %10s\n","MATERIAL","BASE RS","NODES","ERROR");for _,r:=range a.scanRows{fmt.Printf("%-18s %8d %8d %9.2f%%\n",r.Material.Name,r.Material.SignalRS,r.Count,r.Error)};_ = h}
func(a *App)renderTracked(h int){r:=a.trackedMaterials();fmt.Printf("TRACKED MATERIALS\n\n%-18s %10s %10s %10s\n","MATERIAL","OWNED","QUALITY","NEEDED");s,e:=window(a.selected,len(r),h-7);for i:=s;i<e;i++{m:=r[i];inv:=a.inventory(m.ID);need:=a.totalPlannedNeeded(m.ID);fmt.Printf("%s%-18s %10.2f %10.0f %10.2f\n",selmark(i,a.selected),m.Name,inv.Quantity,inv.Quality,need)}}
func(a *App)renderPlanner(h int){r:=a.filteredPlanBlueprints();fmt.Printf("CRAFTING PLANNER [%d blueprints]\n\n%-28s %10s %10s\n","planned","BLUEPRINT","OUTPUT UNITS","BATCH");s,e:=window(a.selected,len(r),h-14);for i:=s;i<e;i++{b:=r[i];p:=a.planItem(b.ID);fmt.Printf("%s%-28s %10.2f %10.2f\n",selmark(i,a.selected),b.Name,p.Crafts,b.Quantity)};fmt.Println("\nMATERIAL ROLL-UP");fmt.Printf("%-18s %10s %10s %10s %10s %s\n","MATERIAL","REQUIRED","OWNED","DEFICIT","QUALITY","STATUS");needs:=a.plannedNeeds();ids:=make([]string,0,len(needs));for id:=range needs{ids=append(ids,id)};sort.Slice(ids,func(i,j int)bool{return a.materialByID(ids[i]).Name<a.materialByID(ids[j]).Name});for _,id:=range ids{m:=a.materialByID(id);n:=needs[id];owned,qual:=0.,0.;if inv:=a.inventory(id);inv!=nil{owned,qual=inv.Quantity,inv.Quality};minq:=a.plannedMinQuality(id);status:="READY";if owned+1e-9<n{status="NEED"};if qual+1e-9<minq{if status!="READY"{status+="+QUALITY"}else{status="QUALITY"}};fmt.Printf("%-18s %10.2f %10.2f %10.2f %10.0f %s\n",m.Name,n,owned,math.Max(0,n-owned),qual,status)};_ = h}
func(a *App)planItem(id string)PlanItem{for _,p:=range a.data.Plan{if p.BlueprintID==id{return p}};return PlanItem{BlueprintID:id}}
func(a *App)filteredPlanBlueprints()[]Blueprint{all:=a.filteredBlueprints();out:=make([]Blueprint,0,len(a.data.Plan));for _,p:=range a.data.Plan{for _,b:=range all{if b.ID==p.BlueprintID{out=append(out,b);break}}};return out}
func(a *App)plannedNeeds()map[string]float64{n:=map[string]float64{};for _,p:=range a.data.Plan{b:=a.blueprintByID(p.BlueprintID);if b==nil||p.Crafts<=0||b.Quantity<=0{continue};mult:=p.Crafts/b.Quantity;for _,r:=range b.Materials{n[r.MaterialID]+=r.Quantity*mult}};return n}
func(a *App)totalPlannedNeeded(id string)float64{return a.plannedNeeds()[id]}
func(a *App)plannedMinQuality(id string)float64{q:=0.;for _,p:=range a.data.Plan{b:=a.blueprintByID(p.BlueprintID);if b==nil{continue};for _,r:=range b.Materials{if r.MaterialID==id&&r.MinQuality>q{q=r.MinQuality}}};return q}
func(a *App)filteredMaterials()[]Material{out:=append([]Material(nil),a.data.Materials...);sort.Slice(out,func(i,j int)bool{return out[i].Name<out[j].Name});if a.filter==""{return out};f:=strings.ToLower(a.filter);r:=out[:0];for _,m:=range out{if strings.Contains(strings.ToLower(m.Name),f)||strings.Contains(strings.ToLower(m.Kind),f)||strings.Contains(strings.ToLower(m.Tier),f){r=append(r,m)}};return r}
func(a *App)filteredBlueprints()[]Blueprint{out:=append([]Blueprint(nil),a.data.Blueprints...);sort.Slice(out,func(i,j int)bool{return out[i].Name<out[j].Name});if a.filter==""{return out};f:=strings.ToLower(a.filter);r:=out[:0];for _,b:=range out{if strings.Contains(strings.ToLower(b.Name),f)||strings.Contains(strings.ToLower(b.Output),f){r=append(r,b)}};return r}
func(a *App)trackedMaterials()[]Material{var r []Material;for _,m:=range a.data.Materials{if a.inventory(m.ID)!=nil{r=append(r,m)}};sort.Slice(r,func(i,j int)bool{return r[i].Name<r[j].Name});return r}
func(a *App)inventory(id string)*Inventory{for i:=range a.data.Inventory{if a.data.Inventory[i].MaterialID==id{return &a.data.Inventory[i]}};return nil}
func removeInventory(in []Inventory,id string)[]Inventory{r:=in[:0];for _,x:=range in{if x.MaterialID!=id{r=append(r,x)}};return r}
func(a *App)materialByID(id string)*Material{for i:=range a.data.Materials{if a.data.Materials[i].ID==id{return &a.data.Materials[i]}};return nil}
func(a *App)blueprintByID(id string)*Blueprint{for i:=range a.data.Blueprints{if a.data.Blueprints[i].ID==id{return &a.data.Blueprints[i]}};return nil}
func(a *App)scanMatch(v int)[]ScanResult{var r []ScanResult;for _,m:=range a.data.Materials{if m.SignalRS<=0{continue};c:=float64(v)/float64(m.SignalRS);n:=int(math.Round(c));if n<1||n>50{continue};err:=math.Abs(float64(v)-float64(n*m.SignalRS))/float64(v)*100;if err<=10{r=append(r,ScanResult{m,n,err})}};sort.Slice(r,func(i,j int)bool{return r[i].Error<r[j].Error});if len(r)>12{r=r[:12]};return r}
func linePrompt(prompt string)(string,error){restoreMode();defer rawMode();fmt.Print("\r\n"+prompt);return strings.TrimSpace(mustReadLine()) ,nil}
func mustReadLine()string{b:=bufio.NewReader(os.Stdin);s,_:=b.ReadString('\n');return s}
func rawMode()error{return exec.Command("stty","-icanon","-echo","min","1","time","0").Run()}
func restoreMode(){_ = exec.Command("stty","sane").Run()}
func readKey(r io.Reader)(byte,error){b:=make([]byte,1);_,e:=r.Read(b);return b[0],e}
func clearScreen(){fmt.Print("\x1b[2J\x1b[H")};func termSize()(int,int){return 100,30};func window(sel,n,rows int)(int,int){if rows<5{rows=5};if n<=rows{return 0,n};s:=sel-rows/2;if s<0{s=0};if s+rows>n{s=n-rows};return s,s+rows};func selmark(i,s int)string{if i==s{return ">"};return " "};func min(a,b int)int{if a<b{return a};return b};func fatal(e error){fmt.Fprintln(os.Stderr,e);os.Exit(1)}
func seedMaterials()[]Material{rows:=[]struct{id,name,tier,kind string;rs int}{{"quantainium","Quantainium","S","Ship Mineable Ore",3170},{"stileron","Stileron","A","Ship Mineable Ore",3185},{"savrilium","Savrilium","A","Ship Mineable Ore",3200},{"ouratite","Ouratite","A","Ship Mineable Ore",3370},{"riccite","Riccite","B","Ship Mineable Ore",3385},{"lindinium","Lindinium","B","Ship Mineable Ore",3400},{"beryl","Beryl","A","Ship Mineable Ore",3540},{"taranite","Taranite","A","Ship Mineable Ore",3555},{"borase","Borase","B","Ship Mineable Ore",3570},{"gold","Gold","A","Ship Mineable Ore",3585},{"bexalite","Bexalite","S","Ship Mineable Ore",3600},{"laranite","Laranite","A","Ship Mineable Ore",3825},{"aslarite","Aslarite","B","Ship Mineable Ore",3840},{"titanium","Titanium","B","Ship Mineable Ore",3855},{"tungsten","Tungsten","B","Ship Mineable Ore",3870},{"agricium","Agricium","A","Ship Mineable Ore",3885},{"torite","Torite","B","Ship Mineable Ore",3900},{"hephaestanite","Hephaestanite","B","Ship Mineable Ore",4180},{"tin","Tin","C","Ship Mineable Ore",4195},{"quartz","Quartz","C","Ship Mineable Ore",4210},{"corundum","Corundum","C","Ship Mineable Ore",4225},{"copper","Copper","C","Ship Mineable Ore",4240},{"silicon","Silicon","C","Ship Mineable Ore",4255},{"iron","Iron","C","Ship Mineable Ore",4270},{"aluminium","Aluminium","C","Ship Mineable Ore",4285},{"ice","Ice","C","Ship Mineable Ore",4300}};out:=make([]Material,0,len(rows));for _,x:=range rows{out=append(out,Material{ID:x.id,Name:x.name,Tier:x.tier,Kind:x.kind,SignalRS:x.rs})};return out}
